language: csharp
mono: none
dist: xenial
os: linux
addons:
    snaps:
      - name: dotnet-sdk
        confinement: classic
        channel: 3.1/stable
solution: NosCore-Discord.sln
branches:
  only: master
install:
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - export PATH="$PATH:$HOME/.local/bin"
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet tool install -g Amazon.Lambda.Tools
before_script:
  - chmod -R a+x scripts
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
  - pip3 install --user awscli
  - pip install --user aws-sam-cli
  - sam --version
script:
  - dotnet --version
  - dotnet restore ./NosCore.TravisLambda/NosCore.Travis/NosCore.Travis.csproj
  - dotnet restore ./NosCore.DonationLambda/NosCore.Donation/NosCore.Donation.csproj
  - dotnet build ./NosCore.TravisLambda/NosCore.Travis/NosCore.Travis.csproj -c Release
  - dotnet build ./NosCore.DonationLambda/NosCore.Donation/NosCore.Donation.csproj -c Release
deploy:
  cleanup: false
  edge: true
  provider: script
  script: bash ./scripts/publish.sh
  on:
    branch: master
after_deploy:
   - ./scripts/after-success.sh
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  
