language: csharp
mono: none
dotnet: 2.1
solution: NosCore-Discord.sln
branches:
  only: master
install:
  - dotnet tool install -g Amazon.Lambda.Tools
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
  - dotnet restore
  - dotnet build
deploy:
  provider: script
  script: dotnet lambda deploy-function noscore-travis --region us-west-2
  skip_cleanup: true
  on:
    branch: master