language: csharp
mono: none
dotnet: 2.1
solution: NosCore-Discord.sln
branches:
  only: master
install:
  - dotnet tool install -g Amazon.Lambda.Tools
  - pip install --user awscli
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
  - cd NosCore.Travis
  - dotnet lambda package
  - cd ./bin/Release/netcoreapp2.1/
  - aws lambda update-function-code --function-name noscore-travis --zip-file fileb://NosCore.Travis.zip
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  