language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.1
solution: NosCore-Discord.sln
branches:
  only: master
install:
  - dotnet tool install -g Amazon.Lambda.Tools
before_script:
  - chmod -R a+x scripts
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
  - ./scripts/publish.sh
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  