name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 8.0.x

    - name: Run Unit Tests
      run: |
        dotnet --version
        dotnet restore ./NosCore.TravisLambda/NosCore.Travis/NosCore.Travis.csproj
        dotnet restore ./NosCore.DonationLambda/NosCore.Donation/NosCore.Donation.csproj
        dotnet build ./NosCore.TravisLambda/NosCore.Travis/NosCore.Travis.csproj -c Release
        dotnet build ./NosCore.DonationLambda/NosCore.Donation/NosCore.Donation.csproj -c Release
    
    - name: Package Lambda
      run: |
        dotnet tool install -g Amazon.Lambda.Tools
        cd NosCore.TravisLambda/NosCore.Travis
        dotnet lambda package
